name: Pull Request
on: pull_request

jobs:
  build:
    runs-on: macos-latest
    env:
      SLN_FILE: NoSamples.sln
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.100-rc.2.22477.23
    - name: Check code formatting
      run: |
        dotnet tool restore
        dotnet fantomas --check -r src samples
    - name: Install dotnet workload
      run: dotnet workload install maui maui-ios maui-android maui-tizen
    - name: Restore
      run: dotnet restore ${SLN_FILE}
    - name: Build
      run: dotnet build --no-restore --configuration Release ${SLN_FILE}
    # - name: Test
    #   run: dotnet test --no-build --configuration Release ${SLN_FILE}